name = "phoenix-blog"
main = "src/index.ts"
compatibility_date = "2023-09-18"

services = [
  { binding = "api", service = "phoenix-api" }
]

[site]
bucket = "./public"

# See https://developers.cloudflare.com/workers/wrangler/bundling/
# and https://developers.cloudflare.com/workers/wrangler/configuration/#bundling
rules = [
  { type = "Text", globs = ["**/*.css"], fallthrough = true },
  { type = "Data", globs = ["**/*.ico"], fallthrough = true },
]


[[r2_buckets]]
binding = "phoenix_storage"
bucket_name = "phoenix"
